module.exports = {
    registerSuccess: "User signup successfully!",
    registerFailed: "Something went worong while user signup!",
    tokenNotProvided: "Token not Provided!!",
    loginSuccess: "User logged in successfully",
    invalidCredentials: "Invalid Credentials!",
    userNotFound: "User Not found!!",
    Unauthorized: "Unauthorized!",
    usernameExist: "Failed! Username is already in use!",
    emailExist: "Failed! Email is already in use!",
    emptyField: "Please fill all required fields",
    checkEmailToResetPassword: "Check your mail to reset your account password",
    EmailNotFoundForResetPassword: "User is not available with this email",
    emailExists: 'User exists with this email address.Please try again with some other email address',
    requiredFirstName: 'First name should not be empty',
    requiredLastName: 'Last name should not be empty',
    requiredUserRole: 'Role should not be empty',
    requiredEmail: 'Email should not be empty',
    requiredPassword: 'Password should not be empty',
    userNotExists: 'User is not exists with this email',
    invalidPassword: 'Invalid password.Please try again with correct password',
    userLoginFailed: 'Something went wrong while user sign-in',
    userInviteSuccess: 'User invited successfully',
    userInviteFailed: 'Something went wrong while inviting user',
    roleNotExists: "Role does not exists",
    requiredVerificationCode: "Verification code should not be empty",
    invalidVerificationCode: "Invalid verification code!",
    accountSetupSuccess: 'Account setup successfully!',
    setupAccountFailed: "Something went wrong while setting up the account",
    imageShouldNotBeEmpty: "Profile image should not be empty",
    userProfileUpdateSuccess: 'Profile image updated successfully',
    userProfileUpdateFailed: 'Something went wrong while updating user profile',
    invalidUserId: 'Invalid user id',
    requiredUserId: "User Id should not be empty",
    userRemoveSuccess: 'User deleted successfully',
    userRemoveFailed: 'Something went wrong while removing user',
    restrictedToDeleteUser: 'You do not have permission to remove user',
    restrictedToUpdateUser: 'You do not have permission to update user details',
    userUpdateSuccess: 'Account details updated successfully',
    userUpdateFailed: 'Something went wrong while updating account'

}